import { Exercise, ExerciseSet } from './exercises';

const conditional = (
  id: string,
  sentence: string,
  translation: string,
  options: [string, string, string],
  correct: number,
  explanation: string,
): Exercise => ({
  id,
  kind: 'Podmiňovací způsob',
  sentence,
  translation,
  task: 'Doplň správný tvar slovesa v přítomném podmiňovacím způsobu.',
  options,
  correct,
  explanation,
});

export const conditionalExerciseSets: ExerciseSet[] = [
  {
    id: 'conditional-are', number: 1, title: 'Pravidelná slovesa I', description: 'Slovesa zakončená na -are',
    reminderTitle: 'KONCOVKY A KMEN', stemReminder: '-ei, -esti, -ebbe, -emmo, -este, -ebbero · parlare → parler-',
    questions: [
      conditional('c1-1', 'Io ___ più lentamente. (parlare)', 'Mluvil/a bych pomaleji.', ['parlerei', 'parlerò', 'parlaresti'], 0, 'Parler- + -ei → parlerei.'),
      conditional('c1-2', 'Tu ___ una casa al mare. (comprare)', 'Koupil/a bys dům u moře.', ['comprerei', 'compreresti', 'comprerebbe'], 1, 'Comprer- + -esti → compreresti.'),
      conditional('c1-3', 'Giulia ___ con noi. (viaggiare)', 'Giulia by cestovala s námi.', ['viaggerei', 'viaggeresti', 'viaggerebbe'], 2, 'Viagger- + -ebbe → viaggerebbe.'),
      conditional('c1-4', 'Noi ___ il museo. (visitare)', 'Navštívili bychom muzeum.', ['visiteremmo', 'visitereste', 'visiterebbero'], 0, 'Visiter- + -emmo → visiteremmo.'),
      conditional('c1-5', 'Voi ___ fino a tardi. (lavorare)', 'Pracovali byste dlouho do večera.', ['lavoreremmo', 'lavorereste', 'lavorerebbero'], 1, 'Lavorer- + -este → lavorereste.'),
      conditional('c1-6', 'I ragazzi ___ in centro. (passeggiare)', 'Chlapci by se procházeli v centru.', ['passeggereste', 'passeggerebbero', 'passeggerebbe'], 1, 'Passegger- + -ebbero → passeggerebbero.'),
      conditional('c1-7', 'Io ___ una torta. (preparare)', 'Připravil/a bych dort.', ['preparerei', 'prepareresti', 'preparerebbe'], 0, 'Preparer- + -ei → preparerei.'),
      conditional('c1-8', 'Noi ___ insieme. (cenare)', 'Večeřeli bychom společně.', ['cenereste', 'ceneremmo', 'cenerebbero'], 1, 'Cener- + -emmo → ceneremmo.'),
      conditional('c1-9', 'Tu ___ questa macchina? (guidare)', 'Řídil/a bys toto auto?', ['guiderebbe', 'guiderei', 'guideresti'], 2, 'Guider- + -esti → guideresti.'),
      conditional('c1-10', 'Le bambine ___ una canzone. (cantare)', 'Dívky by zpívaly píseň.', ['canterebbero', 'cantereste', 'canteremmo'], 0, 'Canter- + -ebbero → canterebbero.'),
    ],
  },
  {
    id: 'conditional-ere', number: 2, title: 'Pravidelná slovesa II', description: 'Slovesa zakončená na -ere',
    reminderTitle: 'KMEN -ERE', stemReminder: 'prendere → prender- · leggere → legger- · stejné koncovky pro všechny třídy',
    questions: [
      conditional('c2-1', 'Io ___ il treno. (prendere)', 'Jel/a bych vlakem.', ['prenderei', 'prenderesti', 'prenderebbe'], 0, 'Prender- + -ei → prenderei.'),
      conditional('c2-2', 'Tu ___ questo libro? (leggere)', 'Přečetl/a bys tuto knihu?', ['leggerei', 'leggeresti', 'leggerebbe'], 1, 'Legger- + -esti → leggeresti.'),
      conditional('c2-3', 'Luca ___ la casa. (vendere)', 'Luca by prodal dům.', ['venderei', 'venderesti', 'venderebbe'], 2, 'Vender- + -ebbe → venderebbe.'),
      conditional('c2-4', 'Noi ___ subito. (rispondere)', 'Odpověděli bychom okamžitě.', ['risponderemmo', 'rispondereste', 'risponderebbero'], 0, 'Risponder- + -emmo → risponderemmo.'),
      conditional('c2-5', 'Voi ___ la porta. (chiudere)', 'Zavřeli byste dveře.', ['chiuderemmo', 'chiudereste', 'chiuderebbero'], 1, 'Chiuder- + -este → chiudereste.'),
      conditional('c2-6', 'Gli studenti ___ l’esercizio. (ripetere)', 'Studenti by zopakovali cvičení.', ['ripetereste', 'ripeterebbero', 'ripeterebbe'], 1, 'Ripeter- + -ebbero → ripeterebbero.'),
      conditional('c2-7', 'Io ___ alla tua storia. (credere)', 'Věřil/a bych tvému příběhu.', ['crederei', 'crederesti', 'crederebbe'], 0, 'Creder- + -ei → crederei.'),
      conditional('c2-8', 'Noi ___ un regalo. (ricevere)', 'Dostali bychom dárek.', ['ricevereste', 'riceveremmo', 'riceverebbero'], 1, 'Ricever- + -emmo → riceveremmo.'),
      conditional('c2-9', 'Tu ___ tutto? (decidere)', 'Rozhodl/a bys o všem?', ['deciderebbe', 'deciderei', 'decideresti'], 2, 'Decider- + -esti → decideresti.'),
      conditional('c2-10', 'I negozi ___ di più. (vendere)', 'Obchody by prodávaly více.', ['venderebbero', 'vendereste', 'venderemmo'], 0, 'Vender- + -ebbero → venderebbero.'),
    ],
  },
  {
    id: 'conditional-ire', number: 3, title: 'Pravidelná slovesa III', description: 'Slovesa zakončená na -ire',
    reminderTitle: 'KMEN -IRE', stemReminder: 'partire → partir- · finire → finir- · v podmiňovacím způsobu se nevkládá -isc-',
    questions: [
      conditional('c3-1', 'Io ___ domani. (partire)', 'Odjel/a bych zítra.', ['partirei', 'partiresti', 'partirebbe'], 0, 'Partir- + -ei → partirei.'),
      conditional('c3-2', 'Tu ___ il lavoro. (finire)', 'Dokončil/a bys práci.', ['finirei', 'finiresti', 'finirebbe'], 1, 'Finir- + -esti → finiresti.'),
      conditional('c3-3', 'Marta ___ la finestra. (aprire)', 'Marta by otevřela okno.', ['aprirei', 'apriresti', 'aprirebbe'], 2, 'Aprir- + -ebbe → aprirebbe.'),
      conditional('c3-4', 'Noi ___ il pacco. (spedire)', 'Poslali bychom balík.', ['spediremmo', 'spedireste', 'spedirebbero'], 0, 'Spedir- + -emmo → spediremmo.'),
      conditional('c3-5', 'Voi ___ meglio qui. (dormire)', 'Spali byste zde lépe.', ['dormiremmo', 'dormireste', 'dormirebbero'], 1, 'Dormir- + -este → dormireste.'),
      conditional('c3-6', 'I bambini ___ la musica. (sentire)', 'Děti by slyšely hudbu.', ['sentireste', 'sentirebbero', 'sentirebbe'], 1, 'Sentir- + -ebbero → sentirebbero.'),
      conditional('c3-7', 'Io ___ una casa. (costruire)', 'Postavil/a bych dům.', ['costruirei', 'costruiresti', 'costruirebbe'], 0, 'Costruir- + -ei → costruirei.'),
      conditional('c3-8', 'Noi ___ la verità. (scoprire)', 'Odhalili bychom pravdu.', ['scoprireste', 'scopriremmo', 'scoprirebbero'], 1, 'Scoprir- + -emmo → scopriremmo.'),
      conditional('c3-9', 'Tu ___ questo consiglio? (seguire)', 'Řídil/a by ses touto radou?', ['seguirebbe', 'seguirei', 'seguiresti'], 2, 'Seguir- + -esti → seguiresti.'),
      conditional('c3-10', 'Le ragazze ___ presto. (partire)', 'Dívky by odjely brzy.', ['partirebbero', 'partireste', 'partiremmo'], 0, 'Partir- + -ebbero → partirebbero.'),
    ],
  },
  {
    id: 'conditional-spelling', number: 4, title: 'Pravidelná slovesa IV', description: 'Pravopisné změny -care, -gare, -ciare, -giare',
    reminderTitle: 'PRAVOPIS', stemReminder: '-care/-gare přidává h · -ciare/-giare zpravidla vypouští i',
    questions: [
      conditional('c4-1', 'Io ___ un albergo. (cercare)', 'Hledal/a bych hotel.', ['cercherei', 'cercerei', 'cercherebbe'], 0, 'Cercare zachová tvrdé k: cercherei.'),
      conditional('c4-2', 'Tu ___ con la carta? (pagare)', 'Zaplatil/a bys kartou?', ['pagerei', 'pagheresti', 'pagherebbe'], 1, 'Pagare přidává h: pagheresti.'),
      conditional('c4-3', 'La lezione ___ più tardi. (cominciare)', 'Hodina by začala později.', ['comincierebbe', 'comincerei', 'comincerebbe'], 2, 'Cominciare vypouští i: comincerebbe.'),
      conditional('c4-4', 'Noi ___ al ristorante. (mangiare)', 'Jedli bychom v restauraci.', ['mangeremmo', 'mangieremmo', 'mangereste'], 0, 'Mangiare vypouští i: mangeremmo.'),
      conditional('c4-5', 'Voi ___ le valigie. (caricare)', 'Naložili byste zavazadla.', ['caricereste', 'carichereste', 'caricherebbero'], 1, 'Caricare přidává h: carichereste.'),
      conditional('c4-6', 'Loro ___ subito. (dimenticare)', 'Okamžitě by zapomněli.', ['dimenticereste', 'dimenticherebbero', 'dimenticherebbe'], 1, 'Dimenticare přidává h: dimenticherebbero.'),
      conditional('c4-7', 'Io ___ domani. (cominciare)', 'Začal/a bych zítra.', ['comincerei', 'comincierei', 'cominceresti'], 0, 'Cominciare → comincerei.'),
      conditional('c4-8', 'Noi ___ tutto online. (pagare)', 'Všechno bychom zaplatili online.', ['paghereste', 'pagheremmo', 'pagherebbero'], 1, 'Pagher- + -emmo → pagheremmo.'),
      conditional('c4-9', 'Tu ___ una pizza? (mangiare)', 'Dal/a by sis pizzu?', ['mangerebbe', 'mangerei', 'mangeresti'], 2, 'Manger- + -esti → mangeresti.'),
      conditional('c4-10', 'I turisti ___ informazioni. (cercare)', 'Turisté by hledali informace.', ['cercherebbero', 'cercerrebbero', 'cerchereste'], 0, 'Cercher- + -ebbero → cercherebbero.'),
    ],
  },
  {
    id: 'conditional-irregular-basic', number: 5, title: 'Nepravidelná slovesa I', description: 'Avere, essere, andare, dare, fare a stare',
    reminderTitle: 'NEPRAVIDELNÉ KMENY', stemReminder: 'avr- · sar- · andr- · dar- · far- · star-',
    questions: [
      conditional('c5-1', 'Io ___ più tempo. (avere)', 'Měl/a bych více času.', ['avrei', 'avresti', 'avrebbe'], 0, 'Avr- + -ei → avrei.'),
      conditional('c5-2', 'Tu ___ più tranquillo. (essere)', 'Byl/a bys klidnější.', ['sarei', 'saresti', 'sarebbe'], 1, 'Sar- + -esti → saresti.'),
      conditional('c5-3', 'Anna ___ al mare. (andare)', 'Anna by jela k moři.', ['andrei', 'andresti', 'andrebbe'], 2, 'Andr- + -ebbe → andrebbe.'),
      conditional('c5-4', 'Noi ___ una risposta. (dare)', 'Dali bychom odpověď.', ['daremmo', 'dareste', 'darebbero'], 0, 'Dar- + -emmo → daremmo.'),
      conditional('c5-5', 'Voi ___ una pausa. (fare)', 'Dali byste si přestávku.', ['faremmo', 'fareste', 'farebbero'], 1, 'Far- + -este → fareste.'),
      conditional('c5-6', 'I nonni ___ con noi. (stare)', 'Prarodiče by zůstali s námi.', ['stareste', 'starebbero', 'starebbe'], 1, 'Star- + -ebbero → starebbero.'),
      conditional('c5-7', 'Io ___ a casa. (essere)', 'Byl/a bych doma.', ['sarei', 'saresti', 'sarebbe'], 0, 'Sar- + -ei → sarei.'),
      conditional('c5-8', 'Noi ___ tutto. (fare)', 'Udělali bychom všechno.', ['fareste', 'faremmo', 'farebbero'], 1, 'Far- + -emmo → faremmo.'),
      conditional('c5-9', 'Tu ___ con noi? (andare)', 'Jel/a bys s námi?', ['andrebbe', 'andrei', 'andresti'], 2, 'Andr- + -esti → andresti.'),
      conditional('c5-10', 'Loro ___ più pazienza. (avere)', 'Měli by více trpělivosti.', ['avrebbero', 'avreste', 'avremmo'], 0, 'Avr- + -ebbero → avrebbero.'),
    ],
  },
  {
    id: 'conditional-irregular-stems', number: 6, title: 'Nepravidelná slovesa II', description: 'Sapere, vedere, vivere, bere a cadere',
    reminderTitle: 'NEPRAVIDELNÉ KMENY', stemReminder: 'sapr- · vedr- · vivr- · berr- · cadr-',
    questions: [
      conditional('c6-1', 'Io ___ la risposta. (sapere)', 'Znal/a bych odpověď.', ['saprei', 'sapresti', 'saprebbe'], 0, 'Sapr- + -ei → saprei.'),
      conditional('c6-2', 'Tu ___ il mare. (vedere)', 'Viděl/a bys moře.', ['vedrei', 'vedresti', 'vedrebbe'], 1, 'Vedr- + -esti → vedresti.'),
      conditional('c6-3', 'Luca ___ in campagna. (vivere)', 'Luca by žil na venkově.', ['vivrei', 'vivresti', 'vivrebbe'], 2, 'Vivr- + -ebbe → vivrebbe.'),
      conditional('c6-4', 'Noi ___ un caffè. (bere)', 'Dali bychom si kávu.', ['berremmo', 'berreste', 'berrebbero'], 0, 'Berr- + -emmo → berremmo.'),
      conditional('c6-5', 'Voi ___ senza aiuto. (cadere)', 'Bez pomoci byste spadli.', ['cadremmo', 'cadreste', 'cadrebbero'], 1, 'Cadr- + -este → cadreste.'),
      conditional('c6-6', 'Le foglie ___ presto. (cadere)', 'Listy by brzy opadaly.', ['cadreste', 'cadrebbero', 'cadrebbe'], 1, 'Cadr- + -ebbero → cadrebbero.'),
      conditional('c6-7', 'Io ___ acqua. (bere)', 'Napil/a bych se vody.', ['berrei', 'berresti', 'berrebbe'], 0, 'Berr- + -ei → berrei.'),
      conditional('c6-8', 'Noi ___ meglio lì. (vivere)', 'Tam bychom žili lépe.', ['vivreste', 'vivremmo', 'vivrebbero'], 1, 'Vivr- + -emmo → vivremmo.'),
      conditional('c6-9', 'Tu ___ tutto. (sapere)', 'Věděl/a bys všechno.', ['saprebbe', 'saprei', 'sapresti'], 2, 'Sapr- + -esti → sapresti.'),
      conditional('c6-10', 'Gli ospiti ___ il giardino. (vedere)', 'Hosté by viděli zahradu.', ['vedrebbero', 'vedreste', 'vedremmo'], 0, 'Vedr- + -ebbero → vedrebbero.'),
    ],
  },
  {
    id: 'conditional-irregular-modal', number: 7, title: 'Nepravidelná slovesa III', description: 'Dovere, potere a volere',
    reminderTitle: 'NEPRAVIDELNÉ KMENY', stemReminder: 'dovere → dovr- · potere → potr- · volere → vorr-',
    questions: [
      conditional('c7-1', 'Io ___ studiare. (dovere)', 'Musel/a bych studovat.', ['dovrei', 'dovresti', 'dovrebbe'], 0, 'Dovr- + -ei → dovrei.'),
      conditional('c7-2', 'Tu ___ aiutarmi? (potere)', 'Mohl/a bys mi pomoci?', ['potrei', 'potresti', 'potrebbe'], 1, 'Potr- + -esti → potresti.'),
      conditional('c7-3', 'Maria ___ un tè. (volere)', 'Maria by chtěla čaj.', ['vorrei', 'vorresti', 'vorrebbe'], 2, 'Vorr- + -ebbe → vorrebbe.'),
      conditional('c7-4', 'Noi ___ partire. (dovere)', 'Museli bychom odjet.', ['dovremmo', 'dovreste', 'dovrebbero'], 0, 'Dovr- + -emmo → dovremmo.'),
      conditional('c7-5', 'Voi ___ entrare. (potere)', 'Mohli byste vstoupit.', ['potremmo', 'potreste', 'potrebbero'], 1, 'Potr- + -este → potreste.'),
      conditional('c7-6', 'I bambini ___ giocare. (volere)', 'Děti by si chtěly hrát.', ['vorreste', 'vorrebbero', 'vorrebbe'], 1, 'Vorr- + -ebbero → vorrebbero.'),
      conditional('c7-7', 'Io ___ una pizza. (volere)', 'Chtěl/a bych pizzu.', ['vorrei', 'vorresti', 'vorrebbe'], 0, 'Vorr- + -ei → vorrei.'),
      conditional('c7-8', 'Noi ___ aspettare. (potere)', 'Mohli bychom počkat.', ['potreste', 'potremmo', 'potrebbero'], 1, 'Potr- + -emmo → potremmo.'),
      conditional('c7-9', 'Tu ___ riposare. (dovere)', 'Měl/a bys odpočívat.', ['dovrebbe', 'dovrei', 'dovresti'], 2, 'Dovr- + -esti → dovresti.'),
      conditional('c7-10', 'Loro ___ restare. (volere)', 'Chtěli by zůstat.', ['vorrebbero', 'vorreste', 'vorremmo'], 0, 'Vorr- + -ebbero → vorrebbero.'),
    ],
  },
  {
    id: 'conditional-irregular-double', number: 8, title: 'Nepravidelná slovesa IV', description: 'Rimanere, tenere a venire',
    reminderTitle: 'NEPRAVIDELNÉ KMENY', stemReminder: 'rimanere → rimarr- · tenere → terr- · venire → verr-',
    questions: [
      conditional('c8-1', 'Io ___ qui. (rimanere)', 'Zůstal/a bych zde.', ['rimarrei', 'rimarresti', 'rimarrebbe'], 0, 'Rimarr- + -ei → rimarrei.'),
      conditional('c8-2', 'Tu ___ il segreto? (tenere)', 'Nechal/a by sis tajemství pro sebe?', ['terrei', 'terresti', 'terrebbe'], 1, 'Terr- + -esti → terresti.'),
      conditional('c8-3', 'Paolo ___ alla festa. (venire)', 'Paolo by přišel na oslavu.', ['verrei', 'verresti', 'verrebbe'], 2, 'Verr- + -ebbe → verrebbe.'),
      conditional('c8-4', 'Noi ___ a casa. (rimanere)', 'Zůstali bychom doma.', ['rimarremmo', 'rimarreste', 'rimarrebbero'], 0, 'Rimarr- + -emmo → rimarremmo.'),
      conditional('c8-5', 'Voi ___ i biglietti. (tenere)', 'Nechali byste si lístky.', ['terremmo', 'terreste', 'terrebbero'], 1, 'Terr- + -este → terreste.'),
      conditional('c8-6', 'Gli amici ___ domani. (venire)', 'Přátelé by přišli zítra.', ['verreste', 'verrebbero', 'verrebbe'], 1, 'Verr- + -ebbero → verrebbero.'),
      conditional('c8-7', 'Io ___ fino a lunedì. (rimanere)', 'Zůstal/a bych do pondělí.', ['rimarrei', 'rimarresti', 'rimarrebbe'], 0, 'Rimarr- + -ei → rimarrei.'),
      conditional('c8-8', 'Noi ___ tutto. (tenere)', 'Všechno bychom si nechali.', ['terreste', 'terremmo', 'terrebbero'], 1, 'Terr- + -emmo → terremmo.'),
      conditional('c8-9', 'Tu ___ con me? (venire)', 'Přišel/přišla bys se mnou?', ['verrebbe', 'verrei', 'verresti'], 2, 'Verr- + -esti → verresti.'),
      conditional('c8-10', 'Loro ___ in città. (rimanere)', 'Zůstali by ve městě.', ['rimarrebbero', 'rimarreste', 'rimarremmo'], 0, 'Rimarr- + -ebbero → rimarrebbero.'),
    ],
  },
  {
    id: 'conditional-irregular-review', number: 9, title: 'Nepravidelná slovesa V', description: 'Opakování uvedených nepravidelných kmenů',
    reminderTitle: 'NEPRAVIDELNÉ KMENY', stemReminder: 'avr-, sar-, andr-, dar-, far-, star-, sapr-, vedr-, vivr-, berr-, cadr-, dovr-, potr-, vorr-, rimarr-, terr-, verr-',
    questions: [
      conditional('c9-1', 'Io ___ la verità. (sapere)', 'Znal/a bych pravdu.', ['saprei', 'sapresti', 'saprebbe'], 0, 'Sapr- + -ei → saprei.'),
      conditional('c9-2', 'Tu ___ più acqua. (bere)', 'Pil/a bys více vody.', ['berrei', 'berresti', 'berrebbe'], 1, 'Berr- + -esti → berresti.'),
      conditional('c9-3', 'Elena ___ con noi. (venire)', 'Elena by přišla s námi.', ['verrei', 'verresti', 'verrebbe'], 2, 'Verr- + -ebbe → verrebbe.'),
      conditional('c9-4', 'Noi ___ una scelta diversa. (fare)', 'Rozhodli bychom se jinak.', ['faremmo', 'fareste', 'farebbero'], 0, 'Far- + -emmo → faremmo.'),
      conditional('c9-5', 'Voi ___ restare. (volere)', 'Chtěli byste zůstat.', ['vorremmo', 'vorreste', 'vorrebbero'], 1, 'Vorr- + -este → vorreste.'),
      conditional('c9-6', 'I ragazzi ___ tutto. (vedere)', 'Chlapci by všechno viděli.', ['vedreste', 'vedrebbero', 'vedrebbe'], 1, 'Vedr- + -ebbero → vedrebbero.'),
      conditional('c9-7', 'Io ___ in Italia. (vivere)', 'Žil/a bych v Itálii.', ['vivrei', 'vivresti', 'vivrebbe'], 0, 'Vivr- + -ei → vivrei.'),
      conditional('c9-8', 'Noi ___ più tempo. (avere)', 'Měli bychom více času.', ['avreste', 'avremmo', 'avrebbero'], 1, 'Avr- + -emmo → avremmo.'),
      conditional('c9-9', 'Tu ___ a Roma? (andare)', 'Jel/a bys do Říma?', ['andrebbe', 'andrei', 'andresti'], 2, 'Andr- + -esti → andresti.'),
      conditional('c9-10', 'Loro ___ qui. (rimanere)', 'Zůstali by zde.', ['rimarrebbero', 'rimarreste', 'rimarremmo'], 0, 'Rimarr- + -ebbero → rimarrebbero.'),
    ],
  },
  {
    id: 'conditional-mixed-review', number: 10, title: 'Smíšené opakování', description: 'Pravidelné i nepravidelné kmeny',
    reminderTitle: 'SMÍŠENÉ CVIČENÍ', stemReminder: 'Nejprve rozhodni, zda je sloveso pravidelné, nebo patří do seznamu nepravidelných.',
    questions: [
      conditional('c10-1', 'Io ___ più spesso. (viaggiare)', 'Cestoval/a bych častěji.', ['viaggerei', 'viaggerebbe', 'viaggeresti'], 0, 'Pravidelné viaggiare → viaggerei.'),
      conditional('c10-2', 'Tu ___ aiutarmi? (potere)', 'Mohl/a bys mi pomoci?', ['potrei', 'potresti', 'potrebbe'], 1, 'Nepravidelný kmen potr- → potresti.'),
      conditional('c10-3', 'Marta ___ il libro. (leggere)', 'Marta by přečetla knihu.', ['leggerei', 'leggeresti', 'leggerebbe'], 2, 'Pravidelné leggere → leggerebbe.'),
      conditional('c10-4', 'Noi ___ a casa. (rimanere)', 'Zůstali bychom doma.', ['rimarremmo', 'rimaneremmo', 'rimarreste'], 0, 'Nepravidelný kmen rimarr- → rimarremmo.'),
      conditional('c10-5', 'Voi ___ il museo. (visitare)', 'Navštívili byste muzeum.', ['visiteremmo', 'visitereste', 'visiterebbero'], 1, 'Pravidelné visitare → visitereste.'),
      conditional('c10-6', 'Gli ospiti ___ un caffè. (bere)', 'Hosté by si dali kávu.', ['berreste', 'berrebbero', 'beverebbero'], 1, 'Nepravidelný kmen berr- → berrebbero.'),
      conditional('c10-7', 'Io ___ la finestra. (aprire)', 'Otevřel/a bych okno.', ['aprirei', 'apriresti', 'aprirebbe'], 0, 'Pravidelné aprire → aprirei.'),
      conditional('c10-8', 'Noi ___ tutto. (sapere)', 'Věděli bychom všechno.', ['sapreste', 'sapremmo', 'saperemmo'], 1, 'Nepravidelný kmen sapr- → sapremmo.'),
      conditional('c10-9', 'Tu ___ la risposta. (scrivere)', 'Napsal/a bys odpověď.', ['scriverebbe', 'scriverei', 'scriveresti'], 2, 'Pravidelné scrivere → scriveresti.'),
      conditional('c10-10', 'Loro ___ con noi. (venire)', 'Přišli by s námi.', ['verrebbero', 'venirebbero', 'verreste'], 0, 'Nepravidelný kmen verr- → verrebbero.'),
    ],
  },
];
