import { Exercise, ExerciseSet } from './exercises';

const future = (
  id: string,
  sentence: string,
  task: string,
  options: [string, string, string],
  correct: number,
  explanation: string,
): Exercise => ({ id, kind: 'Budoucí čas', sentence, task, options, correct, explanation });

export const futureExerciseSets: ExerciseSet[] = [
  {
    id: 'future-are', number: 1, title: 'Pravidelná slovesa I', description: 'Slovesa zakončená na -are',
    questions: [
      future('f1-1', 'Domani io ___ con il direttore. (parlare)', 'Doplň sloveso parlare pro osobu io.', ['parlerò', 'parlarò', 'parlerà'], 0, 'U sloves na -are se a mění na e: parler- + ò → parlerò.'),
      future('f1-2', 'Loro ___ una nuova casa l’anno prossimo. (comprare)', 'Doplň sloveso comprare pro osobu loro.', ['comprerete', 'compreranno', 'compraranno'], 1, 'Kmen je comprer- a koncovka pro loro je -anno → compreranno.'),
      future('f1-3', 'Tu ___ italiano durante il viaggio. (parlare)', 'Doplň sloveso parlare pro osobu tu.', ['parlerà', 'parlerai', 'parlari'], 1, 'Parler- + koncovka -ai pro tu → parlerai.'),
      future('f1-4', 'Noi ___ il museo sabato. (visitare)', 'Doplň sloveso visitare pro osobu noi.', ['visiteremo', 'visitaremo', 'visiterete'], 0, 'Visiter- + koncovka -emo pro noi → visiteremo.'),
      future('f1-5', 'Marta ___ fino a tardi. (lavorare)', 'Doplň sloveso lavorare pro osobu lei.', ['lavorerò', 'lavorerai', 'lavorerà'], 2, 'Lavorer- + koncovka -à pro lei → lavorerà.'),
      future('f1-6', 'Voi ___ la cena per tutti. (preparare)', 'Doplň sloveso preparare pro osobu voi.', ['prepareremo', 'preparerete', 'prepararete'], 1, 'Preparer- + koncovka -ete pro voi → preparerete.'),
      future('f1-7', 'Fra poco io ___ una canzone italiana. (cantare)', 'Doplň sloveso cantare pro osobu io.', ['canterò', 'cantarò', 'canterai'], 0, 'Cantare mění a na e: canter- + ò → canterò.'),
      future('f1-8', 'Noi ___ insieme dopo il lavoro. (cenare)', 'Doplň sloveso cenare pro osobu noi.', ['cenerete', 'cenaremo', 'ceneremo'], 2, 'Cenare mění a na e: cener- + emo → ceneremo.'),
      future('f1-9', 'Tu ___ la macchina domani? (lavare)', 'Doplň sloveso lavare pro osobu tu.', ['laverai', 'lavarai', 'laverà'], 0, 'Laver- + koncovka -ai → laverai.'),
      future('f1-10', 'I ragazzi ___ in centro. (passeggiare)', 'Doplň sloveso passeggiare pro osobu loro.', ['passeggerete', 'passeggieranno', 'passeggeranno'], 2, 'U -giare se před e vypouští i: passegger- + anno → passeggeranno.'),
    ],
  },
  {
    id: 'future-ere', number: 2, title: 'Pravidelná slovesa II', description: 'Slovesa zakončená na -ere',
    questions: [
      future('f2-1', 'L’anno prossimo noi ___ la vecchia casa. (vendere)', 'Doplň sloveso vendere pro osobu noi.', ['venderemo', 'vendremo', 'venderete'], 0, 'Pravidelné vendere: vender- + emo → venderemo.'),
      future('f2-2', 'Tu ___ il treno delle otto. (prendere)', 'Doplň sloveso prendere pro osobu tu.', ['prenderà', 'prenderai', 'prendirai'], 1, 'Prender- + koncovka -ai → prenderai.'),
      future('f2-3', 'La bambina ___ una lettera alla nonna. (scrivere)', 'Doplň sloveso scrivere pro osobu lei.', ['scriverà', 'scriverò', 'scriverai'], 0, 'Scriver- + koncovka -à → scriverà.'),
      future('f2-4', 'Io ___ il giornale in treno. (leggere)', 'Doplň sloveso leggere pro osobu io.', ['leggerai', 'leggerò', 'leggerà'], 1, 'Legger- + koncovka -ò → leggerò.'),
      future('f2-5', 'Voi ___ tutto domani. (decidere)', 'Doplň sloveso decidere pro osobu voi.', ['decideranno', 'decideremo', 'deciderete'], 2, 'Decider- + koncovka -ete → deciderete.'),
      future('f2-6', 'I miei amici ___ il treno delle otto. (perdere)', 'Doplň sloveso perdere pro osobu loro.', ['perderanno', 'perdranno', 'perderete'], 0, 'Pravidelné perdere: perder- + anno → perderanno.'),
      future('f2-7', 'Noi ___ la risposta presto. (ricevere)', 'Doplň sloveso ricevere pro osobu noi.', ['riceverete', 'riceveremo', 'ricevremo'], 1, 'Ricever- + koncovka -emo → riceveremo.'),
      future('f2-8', 'Luca ___ alla tua domanda. (rispondere)', 'Doplň sloveso rispondere pro osobu lui.', ['risponderò', 'risponderà', 'rispondrà'], 1, 'Pravidelné rispondere: risponder- + à → risponderà.'),
      future('f2-9', 'Tu ___ la verità? (credere)', 'Doplň sloveso credere pro osobu tu.', ['crederai', 'credirai', 'crederà'], 0, 'Creder- + koncovka -ai → crederai.'),
      future('f2-10', 'Le studentesse ___ l’esercizio. (ripetere)', 'Doplň sloveso ripetere pro osobu loro.', ['ripeterete', 'ripetiranno', 'ripeteranno'], 2, 'Ripeter- + koncovka -anno → ripeteranno.'),
    ],
  },
  {
    id: 'future-ire', number: 3, title: 'Pravidelná slovesa III', description: 'Slovesa zakončená na -ire',
    questions: [
      future('f3-1', 'Io ___ per Roma lunedì. (partire)', 'Doplň sloveso partire pro osobu io.', ['partirò', 'parterò', 'partirai'], 0, 'Partir- + koncovka -ò → partirò.'),
      future('f3-2', 'Voi ___ il lavoro entro venerdì. (finire)', 'Doplň sloveso finire pro osobu voi.', ['finiremo', 'finirete', 'finiranno'], 1, 'Finir- + koncovka -ete → finirete.'),
      future('f3-3', 'Giulia ___ la finestra. (aprire)', 'Doplň sloveso aprire pro osobu lei.', ['aprerà', 'aprirò', 'aprirà'], 2, 'Aprir- + koncovka -à → aprirà.'),
      future('f3-4', 'Noi ___ un pacco domani. (spedire)', 'Doplň sloveso spedire pro osobu noi.', ['spediremo', 'spederemo', 'spedirete'], 0, 'Spedir- + koncovka -emo → spediremo.'),
      future('f3-5', 'Tu ___ bene questa notte. (dormire)', 'Doplň sloveso dormire pro osobu tu.', ['dormerai', 'dormirai', 'dormirà'], 1, 'Dormir- + koncovka -ai → dormirai.'),
      future('f3-6', 'I bambini ___ il rumore. (sentire)', 'Doplň sloveso sentire pro osobu loro.', ['sentirete', 'senteranno', 'sentiranno'], 2, 'Sentir- + koncovka -anno → sentiranno.'),
      future('f3-7', 'Io ___ una casa vicino al mare. (costruire)', 'Doplň sloveso costruire pro osobu io.', ['costruirò', 'costruerò', 'costruirai'], 0, 'Costruir- + koncovka -ò → costruirò.'),
      future('f3-8', 'Noi ___ la porta alle nove. (aprire)', 'Doplň sloveso aprire pro osobu noi.', ['aprirete', 'apriremo', 'apreremo'], 1, 'Aprir- + koncovka -emo → apriremo.'),
      future('f3-9', 'Voi ___ il discorso con attenzione. (sentire)', 'Doplň sloveso sentire pro osobu voi.', ['sentirete', 'senterete', 'sentiranno'], 0, 'Sentir- + koncovka -ete → sentirete.'),
      future('f3-10', 'Marco e Anna ___ insieme. (partire)', 'Doplň sloveso partire pro osobu loro.', ['partirete', 'parteranno', 'partiranno'], 2, 'Partir- + koncovka -anno → partiranno.'),
    ],
  },
  {
    id: 'future-spelling', number: 4, title: 'Pravidelná slovesa IV', description: 'Pravopisné změny -care, -gare, -ciare, -giare',
    questions: [
      future('f4-1', 'Io ___ un hotel economico. (cercare)', 'Doplň sloveso cercare pro osobu io.', ['cercherò', 'cercerò', 'cercherai'], 0, 'Slovesa na -care vkládají h pro zachování tvrdého k: cercherò.'),
      future('f4-2', 'Tu ___ il conto con la carta. (pagare)', 'Doplň sloveso pagare pro osobu tu.', ['pagerai', 'pagherai', 'pagherà'], 1, 'Slovesa na -gare vkládají h: pagher- + ai → pagherai.'),
      future('f4-3', 'La lezione ___ alle nove. (cominciare)', 'Doplň sloveso cominciare pro osobu lei.', ['comincierà', 'comincerò', 'comincerà'], 2, 'U -ciare se před e vypouští i: comincerà.'),
      future('f4-4', 'Noi ___ al ristorante. (mangiare)', 'Doplň sloveso mangiare pro osobu noi.', ['mangeremo', 'mangieremo', 'mangerete'], 0, 'U -giare se vypouští i: manger- + emo → mangeremo.'),
      future('f4-5', 'Voi ___ il documento online. (caricare)', 'Doplň sloveso caricare pro osobu voi.', ['caricerete', 'caricherete', 'caricheranno'], 1, 'Caricare zachovává tvrdé k pomocí h → caricherete.'),
      future('f4-6', 'Loro ___ in contanti. (pagare)', 'Doplň sloveso pagare pro osobu loro.', ['pageranno', 'pagherete', 'pagheranno'], 2, 'Pagare → pagher- + anno → pagheranno.'),
      future('f4-7', 'Io ___ il libro domani. (cominciare)', 'Doplň sloveso cominciare pro osobu io.', ['comincerò', 'comincierò', 'comincerai'], 0, 'Cominciare → comincer- + ò → comincerò.'),
      future('f4-8', 'Noi ___ le valigie in macchina. (caricare)', 'Doplň sloveso caricare pro osobu noi.', ['cariceremo', 'caricheremo', 'caricherete'], 1, 'Caricare → caricher- + emo → caricheremo.'),
      future('f4-9', 'Tu ___ una pizza intera? (mangiare)', 'Doplň sloveso mangiare pro osobu tu.', ['mangerai', 'mangierai', 'mangerà'], 0, 'Mangiare → manger- + ai → mangerai.'),
      future('f4-10', 'Gli studenti ___ le parole nel testo. (cercare)', 'Doplň sloveso cercare pro osobu loro.', ['cerceranno', 'cercherete', 'cercheranno'], 2, 'Cercare → cercher- + anno → cercheranno.'),
    ],
  },
  {
    id: 'future-regular-review', number: 5, title: 'Pravidelná slovesa V', description: 'Smíšené opakování všech koncovek',
    questions: [
      future('f5-1', 'Domani noi ___ presto. (partire)', 'Doplň sloveso partire pro osobu noi.', ['partiremo', 'parteremo', 'partirete'], 0, 'Partir- + emo → partiremo.'),
      future('f5-2', 'Tu ___ una torta per la festa. (preparare)', 'Doplň sloveso preparare pro osobu tu.', ['preparerà', 'preparerai', 'prepararai'], 1, 'Preparer- + ai → preparerai.'),
      future('f5-3', 'Paolo ___ il contratto. (leggere)', 'Doplň sloveso leggere pro osobu lui.', ['leggerò', 'leggerai', 'leggerà'], 2, 'Legger- + à → leggerà.'),
      future('f5-4', 'Io ___ una risposta entro sera. (ricevere)', 'Doplň sloveso ricevere pro osobu io.', ['riceverò', 'ricevrò', 'riceverai'], 0, 'Ricever- + ò → riceverò.'),
      future('f5-5', 'Voi ___ il centro storico. (visitare)', 'Doplň sloveso visitare pro osobu voi.', ['visiteremo', 'visiterete', 'visitarete'], 1, 'Visiter- + ete → visiterete.'),
      future('f5-6', 'Le ragazze ___ la cena. (finire)', 'Doplň sloveso finire pro osobu loro.', ['finirete', 'fineranno', 'finiranno'], 2, 'Finir- + anno → finiranno.'),
      future('f5-7', 'Io ___ le chiavi sul tavolo. (lasciare)', 'Doplň sloveso lasciare pro osobu io.', ['lascerò', 'lascierò', 'lascerai'], 0, 'Lasciare vypouští i: lascer- + ò → lascerò.'),
      future('f5-8', 'Noi ___ una nuova lingua. (imparare)', 'Doplň sloveso imparare pro osobu noi.', ['imparerete', 'impareremo', 'impararemo'], 1, 'Imparer- + emo → impareremo.'),
      future('f5-9', 'Tu ___ la porta prima di uscire. (chiudere)', 'Doplň sloveso chiudere pro osobu tu.', ['chiuderai', 'chiudirai', 'chiuderà'], 0, 'Chiuder- + ai → chiuderai.'),
      future('f5-10', 'I turisti ___ molte fotografie. (scattare)', 'Doplň sloveso scattare pro osobu loro.', ['scatterete', 'scattaranno', 'scatteranno'], 2, 'Scattare mění a na e: scatter- + anno → scatteranno.'),
    ],
  },
  {
    id: 'future-essere-avere', number: 6, title: 'Nepravidelná slovesa I', description: 'Essere a avere', stemReminder: 'essere → sar- · avere → avr-',
    questions: [
      future('f6-1', 'Io ___ a casa dopo le sei. (essere)', 'Doplň essere pro osobu io.', ['sarò', 'esserò', 'sarai'], 0, 'Kmen sar- + ò → sarò.'),
      future('f6-2', 'Tu ___ molto lavoro domani. (avere)', 'Doplň avere pro osobu tu.', ['averai', 'avrai', 'avrà'], 1, 'Kmen avr- + ai → avrai.'),
      future('f6-3', 'Giulia ___ felice del regalo. (essere)', 'Doplň essere pro osobu lei.', ['sarò', 'sarai', 'sarà'], 2, 'Kmen sar- + à → sarà.'),
      future('f6-4', 'Noi ___ più tempo in estate. (avere)', 'Doplň avere pro osobu noi.', ['avremo', 'averemo', 'avrete'], 0, 'Kmen avr- + emo → avremo.'),
      future('f6-5', 'Voi ___ i primi ad arrivare. (essere)', 'Doplň essere pro osobu voi.', ['saremo', 'sarete', 'saranno'], 1, 'Kmen sar- + ete → sarete.'),
      future('f6-6', 'I bambini ___ fame dopo la partita. (avere)', 'Doplň avere pro osobu loro.', ['avrete', 'averanno', 'avranno'], 2, 'Kmen avr- + anno → avranno.'),
      future('f6-7', 'Io ___ bisogno del tuo aiuto. (avere)', 'Doplň avere pro osobu io.', ['avrò', 'averò', 'avrai'], 0, 'Kmen avr- + ò → avrò.'),
      future('f6-8', 'Noi ___ pronti alle otto. (essere)', 'Doplň essere pro osobu noi.', ['sarete', 'saremo', 'esseremo'], 1, 'Kmen sar- + emo → saremo.'),
      future('f6-9', 'Tu ___ in ufficio lunedì? (essere)', 'Doplň essere pro osobu tu.', ['sarai', 'esserai', 'sarà'], 0, 'Kmen sar- + ai → sarai.'),
      future('f6-10', 'Marco e Lucia ___ una sorpresa. (avere)', 'Doplň avere pro osobu loro.', ['averanno', 'avrete', 'avranno'], 2, 'Kmen avr- + anno → avranno.'),
    ],
  },
  {
    id: 'future-andare-fare-stare', number: 7, title: 'Nepravidelná slovesa II', description: 'Andare, fare a stare', stemReminder: 'andare → andr- · fare → far- · stare → star-',
    questions: [
      future('f7-1', 'Domani io ___ dal dentista. (andare)', 'Doplň andare pro osobu io.', ['andrò', 'anderò', 'andrai'], 0, 'Kmen andr- + ò → andrò.'),
      future('f7-2', 'Tu ___ una torta per il compleanno. (fare)', 'Doplň fare pro osobu tu.', ['farà', 'farai', 'facerai'], 1, 'Kmen far- + ai → farai.'),
      future('f7-3', 'Marta ___ a casa stasera. (stare)', 'Doplň stare pro osobu lei.', ['starò', 'starai', 'starà'], 2, 'Kmen star- + à → starà.'),
      future('f7-4', 'Noi ___ in montagna domenica. (andare)', 'Doplň andare pro osobu noi.', ['andremo', 'anderemo', 'andrete'], 0, 'Kmen andr- + emo → andremo.'),
      future('f7-5', 'Voi ___ attenzione alla spiegazione. (fare)', 'Doplň fare pro osobu voi.', ['faremo', 'farete', 'faranno'], 1, 'Kmen far- + ete → farete.'),
      future('f7-6', 'I nonni ___ con noi per una settimana. (stare)', 'Doplň stare pro osobu loro.', ['starete', 'starano', 'staranno'], 2, 'Kmen star- + anno → staranno.'),
      future('f7-7', 'Io ___ del mio meglio. (fare)', 'Doplň fare pro osobu io.', ['farò', 'facerò', 'farai'], 0, 'Kmen far- + ò → farò.'),
      future('f7-8', 'Noi ___ bene in questo albergo. (stare)', 'Doplň stare pro osobu noi.', ['starete', 'staremo', 'starremo'], 1, 'Kmen star- + emo → staremo.'),
      future('f7-9', 'Tu ___ al concerto con Laura? (andare)', 'Doplň andare pro osobu tu.', ['andrai', 'anderai', 'andrà'], 0, 'Kmen andr- + ai → andrai.'),
      future('f7-10', 'Gli studenti ___ molte domande. (fare)', 'Doplň fare pro osobu loro.', ['farano', 'farete', 'faranno'], 2, 'Kmen far- + anno → faranno.'),
    ],
  },
  {
    id: 'future-venire-tenere-rimanere', number: 8, title: 'Nepravidelná slovesa III', description: 'Venire, tenere a rimanere', stemReminder: 'venire → verr- · tenere → terr- · rimanere → rimarr-',
    questions: [
      future('f8-1', 'Io ___ alla festa con Paolo. (venire)', 'Doplň venire pro osobu io.', ['verrò', 'venirò', 'verrai'], 0, 'Kmen verr- + ò → verrò.'),
      future('f8-2', 'Tu ___ questo segreto per te. (tenere)', 'Doplň tenere pro osobu tu.', ['tenerai', 'terrai', 'terrà'], 1, 'Kmen terr- + ai → terrai.'),
      future('f8-3', 'Elena ___ a Roma per due giorni. (rimanere)', 'Doplň rimanere pro osobu lei.', ['rimanerà', 'rimarrò', 'rimarrà'], 2, 'Kmen rimarr- + à → rimarrà.'),
      future('f8-4', 'Noi ___ a trovarti presto. (venire)', 'Doplň venire pro osobu noi.', ['verremo', 'veniremo', 'verrete'], 0, 'Kmen verr- + emo → verremo.'),
      future('f8-5', 'Voi ___ i documenti originali. (tenere)', 'Doplň tenere pro osobu voi.', ['terremo', 'terrete', 'terranno'], 1, 'Kmen terr- + ete → terrete.'),
      future('f8-6', 'I negozi ___ chiusi domenica. (rimanere)', 'Doplň rimanere pro osobu loro.', ['rimarrete', 'rimaneranno', 'rimarranno'], 2, 'Kmen rimarr- + anno → rimarranno.'),
      future('f8-7', 'Io ___ la promessa. (mantenere)', 'Doplň mantenere pro osobu io.', ['manterrò', 'mantenerò', 'manterrai'], 0, 'Mantenere se řídí podle tenere: kmen manterr- + ò → manterrò.'),
      future('f8-8', 'Noi ___ a casa se pioverà. (rimanere)', 'Doplň rimanere pro osobu noi.', ['rimarrete', 'rimarremo', 'rimaneremo'], 1, 'Kmen rimarr- + emo → rimarremo.'),
      future('f8-9', 'Tu ___ con noi domani? (venire)', 'Doplň venire pro osobu tu.', ['verrai', 'venirai', 'verrà'], 0, 'Kmen verr- + ai → verrai.'),
      future('f8-10', 'Gli atleti ___ un ritmo costante. (mantenere)', 'Doplň mantenere pro osobu loro.', ['manteneranno', 'manterrete', 'manterranno'], 2, 'Kmen manterr- + anno → manterranno.'),
    ],
  },
  {
    id: 'future-modal', number: 9, title: 'Nepravidelná slovesa IV', description: 'Potere, dovere, volere, sapere, vedere', stemReminder: 'potere → potr- · dovere → dovr- · volere → vorr- · sapere → sapr- · vedere → vedr-',
    questions: [
      future('f9-1', 'Io ___ aiutarti domani. (potere)', 'Doplň potere pro osobu io.', ['potrò', 'poterò', 'potrai'], 0, 'Kmen potr- + ò → potrò.'),
      future('f9-2', 'Tu ___ partire molto presto. (dovere)', 'Doplň dovere pro osobu tu.', ['doverai', 'dovrai', 'dovrà'], 1, 'Kmen dovr- + ai → dovrai.'),
      future('f9-3', 'Francesca ___ un caffè. (volere)', 'Doplň volere pro osobu lei.', ['volerà', 'vorrò', 'vorrà'], 2, 'Kmen vorr- + à → vorrà.'),
      future('f9-4', 'Noi ___ la risposta domani. (sapere)', 'Doplň sapere pro osobu noi.', ['sapremo', 'saperemo', 'saprete'], 0, 'Kmen sapr- + emo → sapremo.'),
      future('f9-5', 'Voi ___ il mare dalla finestra. (vedere)', 'Doplň vedere pro osobu voi.', ['vedremo', 'vedrete', 'vederete'], 1, 'Kmen vedr- + ete → vedrete.'),
      future('f9-6', 'Loro non ___ venire alla riunione. (potere)', 'Doplň potere pro osobu loro.', ['potrete', 'poteranno', 'potranno'], 2, 'Kmen potr- + anno → potranno.'),
      future('f9-7', 'Io ___ studiare di più. (dovere)', 'Doplň dovere pro osobu io.', ['dovrò', 'doverò', 'dovrai'], 0, 'Kmen dovr- + ò → dovrò.'),
      future('f9-8', 'Noi ___ visitare Firenze. (volere)', 'Doplň volere pro osobu noi.', ['vorrete', 'vorremo', 'voleremo'], 1, 'Kmen vorr- + emo → vorremo.'),
      future('f9-9', 'Tu ___ tutto al momento giusto. (sapere)', 'Doplň sapere pro osobu tu.', ['saprai', 'saperai', 'saprà'], 0, 'Kmen sapr- + ai → saprai.'),
      future('f9-10', 'I ragazzi ___ i loro amici sabato. (vedere)', 'Doplň vedere pro osobu loro.', ['vederanno', 'vedrete', 'vedranno'], 2, 'Kmen vedr- + anno → vedranno.'),
    ],
  },
  {
    id: 'future-irregular-review', number: 10, title: 'Nepravidelná slovesa V', description: 'Závěrečné smíšené opakování', stemReminder: 'bere → berr- · vivere → vivr- · morire → morr- · porre → porr- · tradurre → tradurr- · cadere → cadr-',
    questions: [
      future('f10-1', 'Io ___ un bicchiere d’acqua. (bere)', 'Doplň bere pro osobu io.', ['berrò', 'beverò', 'berrai'], 0, 'Kmen berr- + ò → berrò.'),
      future('f10-2', 'Tu ___ a lungo e felicemente. (vivere)', 'Doplň vivere pro osobu tu.', ['viverai', 'vivrai', 'vivrà'], 1, 'Kmen vivr- + ai → vivrai.'),
      future('f10-3', 'La pianta ___ senza acqua. (morire)', 'Doplň morire pro osobu lei.', ['morirà', 'morrò', 'morrà'], 2, 'Kmen morr- + à → morrà.'),
      future('f10-4', 'Noi ___ una domanda al professore. (porre)', 'Doplň porre pro osobu noi.', ['porremo', 'poneremo', 'porrete'], 0, 'Kmen porr- + emo → porremo.'),
      future('f10-5', 'Voi ___ il testo in italiano. (tradurre)', 'Doplň tradurre pro osobu voi.', ['tradurremo', 'traducerete', 'tradurrete'], 2, 'Kmen tradurr- + ete → tradurrete.'),
      future('f10-6', 'Le foglie ___ in autunno. (cadere)', 'Doplň cadere pro osobu loro.', ['caderanno', 'cadrete', 'cadranno'], 2, 'Kmen cadr- + anno → cadranno.'),
      future('f10-7', 'Io ___ la proposta domani. (proporre)', 'Doplň proporre pro osobu io.', ['proporrò', 'proponerò', 'proporrai'], 0, 'Proporre se řídí podle porre: proporr- + ò → proporrò.'),
      future('f10-8', 'Noi ___ in campagna. (vivere)', 'Doplň vivere pro osobu noi.', ['vivrete', 'vivremo', 'viveremo'], 1, 'Kmen vivr- + emo → vivremo.'),
      future('f10-9', 'Tu ___ il vino o l’acqua? (bere)', 'Doplň bere pro osobu tu.', ['berrai', 'beverai', 'berrà'], 0, 'Kmen berr- + ai → berrai.'),
      future('f10-10', 'Gli interpreti ___ il discorso. (tradurre)', 'Doplň tradurre pro osobu loro.', ['tradurrano', 'tradurrete', 'tradurranno'], 2, 'Kmen tradurr- + anno → tradurranno.'),
    ],
  },
];

export const getFutureExerciseSet = (id: string): ExerciseSet | undefined =>
  futureExerciseSets.find((set) => set.id === id);
