import { Exercise, ExerciseSet } from './exercises';

const present = (
  id: string,
  sentence: string,
  translation: string,
  task: string,
  options: [string, string, string],
  correct: number,
  explanation: string,
): Exercise => ({ id, kind: 'Přítomný čas', sentence, translation, task, options, correct, explanation });

export const presentExerciseSets: ExerciseSet[] = [
  {
    id: 'present-are-endings', number: 1, title: 'Slovesa na -are I', description: 'Základní koncovky',
    reminderTitle: 'KONCOVKY -ARE', stemReminder: 'io -o · tu -i · lui/lei -a · noi -iamo · voi -ate · loro -ano',
    questions: [
      present('p1-1', 'Io ___ italiano ogni giorno. (studiare)', 'Každý den studuji italštinu.', 'Doplň tvar pro io.', ['studio', 'studi', 'studia'], 0, 'Studiare: kmen studi- + -o → studio.'),
      present('p1-2', 'Tu ___ molto bene. (cantare)', 'Zpíváš velmi dobře.', 'Doplň tvar pro tu.', ['canto', 'canti', 'canta'], 1, 'Cantare: cant- + -i → canti.'),
      present('p1-3', 'Marco ___ in centro. (lavorare)', 'Marco pracuje v centru.', 'Doplň tvar pro lui.', ['lavoro', 'lavori', 'lavora'], 2, 'Lavorare: lavor- + -a → lavora.'),
      present('p1-4', 'Noi ___ la televisione. (guardare)', 'Díváme se na televizi.', 'Doplň tvar pro noi.', ['guardiamo', 'guardate', 'guardano'], 0, 'Guardare: guard- + -iamo → guardiamo.'),
      present('p1-5', 'Voi ___ a casa stasera. (cenare)', 'Dnes večer večeříte doma.', 'Doplň tvar pro voi.', ['ceniamo', 'cenate', 'cenano'], 1, 'Cenare: cen- + -ate → cenate.'),
      present('p1-6', 'I bambini ___ nel parco. (giocare)', 'Děti si hrají v parku.', 'Doplň tvar pro loro.', ['giocate', 'gioca', 'giocano'], 2, 'Giocare: pro loro použijeme giocano.'),
      present('p1-7', 'Io ___ la radio ogni mattina. (ascoltare)', 'Každé ráno poslouchám rádio.', 'Doplň tvar pro io.', ['ascolto', 'ascolti', 'ascolta'], 0, 'Ascoltare: ascolt- + -o → ascolto.'),
      present('p1-8', 'Noi ___ una nuova lingua. (imparare)', 'Učíme se nový jazyk.', 'Doplň tvar pro noi.', ['imparate', 'impariamo', 'imparano'], 1, 'Imparare: impar- + -iamo → impariamo.'),
      present('p1-9', 'Tu ___ spesso tua nonna. (chiamare)', 'Často voláš své babičce.', 'Doplň tvar pro tu.', ['chiami', 'chiamo', 'chiama'], 0, 'Chiamare: chiam- + -i → chiami.'),
      present('p1-10', 'Le ragazze ___ insieme. (ballare)', 'Dívky tančí společně.', 'Doplň tvar pro loro.', ['ballate', 'balla', 'ballano'], 2, 'Ballare: ball- + -ano → ballano.'),
    ],
  },
  {
    id: 'present-are-spelling', number: 2, title: 'Slovesa na -are II', description: 'Pravopis, zápor a otázky',
    reminderTitle: 'PRAVOPIS -CARE/-GARE', stemReminder: 'Před -i a -iamo se přidává h: cerchi, cerchiamo; paghi, paghiamo.',
    questions: [
      present('p2-1', 'Io ___ un nuovo lavoro. (cercare)', 'Hledám novou práci.', 'Doplň tvar pro io.', ['cerco', 'cerchi', 'cerca'], 0, 'Pro io zůstává tvrdé c: cerco.'),
      present('p2-2', 'Tu ___ con la carta? (pagare)', 'Platíš kartou?', 'Doplň tvar pro tu.', ['pagi', 'paghi', 'paga'], 1, 'Před -i vložíme h: paghi.'),
      present('p2-3', 'La lezione ___ alle nove. (cominciare)', 'Hodina začíná v devět.', 'Doplň tvar pro lei.', ['comincio', 'cominci', 'comincia'], 2, 'Pro lui/lei má -are koncovku -a: comincia.'),
      present('p2-4', 'Noi ___ al ristorante. (mangiare)', 'Jíme v restauraci.', 'Doplň tvar pro noi.', ['mangiamo', 'manghiamo', 'mangiate'], 0, 'Mangiare tvoří noi mangiamo; druhé i se nepřidává.'),
      present('p2-5', 'Voi non ___ a calcio. (giocare)', 'Nehrajete fotbal.', 'Doplň zápornou větu.', ['giochiamo', 'giocate', 'giocano'], 1, 'Pro voi: non giocate.'),
      present('p2-6', 'Gli studenti ___ molto. (studiare)', 'Studenti hodně studují.', 'Doplň tvar pro loro.', ['studiate', 'studia', 'studiano'], 2, 'Studiare: pro loro studiano.'),
      present('p2-7', 'Io non ___ la macchina oggi. (usare)', 'Dnes nepoužívám auto.', 'Doplň zápornou větu.', ['uso', 'usi', 'usa'], 0, 'Non stojí před slovesem; io uso.'),
      present('p2-8', 'Noi ___ il museo ogni domenica. (visitare)', 'Každou neděli navštěvujeme muzeum.', 'Doplň tvar pro noi.', ['visitate', 'visitiamo', 'visitano'], 1, 'Visitare: visit- + -iamo → visitiamo.'),
      present('p2-9', '___ spesso in treno? (viaggiare, tu)', 'Cestuješ často vlakem?', 'Doplň otázku.', ['Viaggi', 'Viaggio', 'Viaggia'], 0, 'Pro tu: viaggi; otázka nemění slovesný tvar.'),
      present('p2-10', 'Paolo e Sara ___ una casa. (affittare)', 'Paolo a Sara si pronajímají dům.', 'Doplň tvar pro loro.', ['affittate', 'affitta', 'affittano'], 2, 'Dvě osoby jsou loro: affittano.'),
    ],
  },
  {
    id: 'present-ere-endings', number: 3, title: 'Slovesa na -ere I', description: 'Základní koncovky',
    reminderTitle: 'KONCOVKY -ERE', stemReminder: 'io -o · tu -i · lui/lei -e · noi -iamo · voi -ete · loro -ono',
    questions: [
      present('p3-1', 'Io ___ un caffè. (prendere)', 'Dávám si kávu.', 'Doplň tvar pro io.', ['prendo', 'prendi', 'prende'], 0, 'Prendere: prend- + -o → prendo.'),
      present('p3-2', 'Tu ___ in questa storia? (credere)', 'Věříš tomuto příběhu?', 'Doplň tvar pro tu.', ['credo', 'credi', 'crede'], 1, 'Credere: cred- + -i → credi.'),
      present('p3-3', 'Anna ___ una lettera. (scrivere)', 'Anna píše dopis.', 'Doplň tvar pro lei.', ['scrivo', 'scrivi', 'scrive'], 2, 'Scrivere: scriv- + -e → scrive.'),
      present('p3-4', 'Noi ___ la macchina. (vendere)', 'Prodáváme auto.', 'Doplň tvar pro noi.', ['vendiamo', 'vendete', 'vendono'], 0, 'Vendere: vend- + -iamo → vendiamo.'),
      present('p3-5', 'Voi ___ molti messaggi. (ricevere)', 'Dostáváte mnoho zpráv.', 'Doplň tvar pro voi.', ['riceviamo', 'ricevete', 'ricevono'], 1, 'Ricevere: ricev- + -ete → ricevete.'),
      present('p3-6', 'I ragazzi ___ alla domanda. (rispondere)', 'Chlapci odpovídají na otázku.', 'Doplň tvar pro loro.', ['rispondete', 'risponde', 'rispondono'], 2, 'Rispondere: rispond- + -ono → rispondono.'),
      present('p3-7', 'Io ___ la finestra. (chiudere)', 'Zavírám okno.', 'Doplň tvar pro io.', ['chiudo', 'chiudi', 'chiude'], 0, 'Chiudere: chiud- + -o → chiudo.'),
      present('p3-8', 'Noi ___ in una piccola città. (vivere)', 'Žijeme v malém městě.', 'Doplň tvar pro noi.', ['vivete', 'viviamo', 'vivono'], 1, 'Vivere: viv- + -iamo → viviamo.'),
      present('p3-9', 'Tu ___ spesso le chiavi. (perdere)', 'Často ztrácíš klíče.', 'Doplň tvar pro tu.', ['perdi', 'perdo', 'perde'], 0, 'Perdere: perd- + -i → perdi.'),
      present('p3-10', 'Le aziende ___ nuovi prodotti. (vendere)', 'Firmy prodávají nové výrobky.', 'Doplň tvar pro loro.', ['vendete', 'vende', 'vendono'], 2, 'Le aziende jsou loro: vendono.'),
    ],
  },
  {
    id: 'present-ere-context', number: 4, title: 'Slovesa na -ere II', description: 'Věty, otázky a zápor',
    reminderTitle: 'PRAVIDLO', stemReminder: 'Od infinitivu odeber -ere a přidej koncovku. Non stojí před slovesem; otázka tvar nemění.',
    questions: [
      present('p4-1', 'Io non ___ la risposta. (conoscere)', 'Neznám odpověď.', 'Doplň zápornou větu.', ['conosco', 'conosci', 'conosce'], 0, 'Pro io je správně conosco: non conosco.'),
      present('p4-2', 'Tu ___ la porta? (chiudere)', 'Zavíráš dveře?', 'Doplň otázku.', ['chiudo', 'chiudi', 'chiude'], 1, 'Pro tu: chiudi.'),
      present('p4-3', 'Il negozio ___ prodotti italiani. (vendere)', 'Obchod prodává italské výrobky.', 'Doplň tvar pro lui.', ['vendo', 'vendi', 'vende'], 2, 'Il negozio je lui: vende.'),
      present('p4-4', 'Noi ___ molte e-mail. (ricevere)', 'Dostáváme mnoho e-mailů.', 'Doplň tvar pro noi.', ['riceviamo', 'ricevete', 'ricevono'], 0, 'Pro noi: riceviamo.'),
      present('p4-5', 'Voi non ___ alla domanda. (rispondere)', 'Neodpovídáte na otázku.', 'Doplň zápornou větu.', ['rispondiamo', 'rispondete', 'rispondono'], 1, 'Pro voi: non rispondete.'),
      present('p4-6', 'Gli studenti ___ il testo. (comprendere)', 'Studenti rozumějí textu.', 'Doplň tvar pro loro.', ['comprendete', 'comprende', 'comprendono'], 2, 'Gli studenti jsou loro: comprendono.'),
      present('p4-7', 'Io ___ il freddo. (temere)', 'Bojím se chladu.', 'Doplň tvar pro io.', ['temo', 'temi', 'teme'], 0, 'Temere: tem- + -o → temo.'),
      present('p4-8', 'Noi ___ molto nel progetto. (credere)', 'Tomuto projektu velmi věříme.', 'Doplň tvar pro noi.', ['credete', 'crediamo', 'credono'], 1, 'Credere: cred- + -iamo → crediamo.'),
      present('p4-9', '___ qui vicino? (vivere, tu)', 'Bydlíš tady poblíž?', 'Doplň otázku.', ['Vivi', 'Vivo', 'Vive'], 0, 'Pro tu: vivi.'),
      present('p4-10', 'Marco e Lucia ___ la stessa opinione. (condividere)', 'Marco a Lucia sdílejí stejný názor.', 'Doplň tvar pro loro.', ['condividete', 'condivide', 'condividono'], 2, 'Dvě osoby jsou loro: condividono.'),
    ],
  },
  {
    id: 'present-ire-regular', number: 5, title: 'Slovesa na -ire I', description: 'Typ dormire bez -isc-',
    reminderTitle: 'KONCOVKY -IRE', stemReminder: 'io -o · tu -i · lui/lei -e · noi -iamo · voi -ite · loro -ono',
    questions: [
      present('p5-1', 'Io ___ otto ore. (dormire)', 'Spím osm hodin.', 'Doplň tvar pro io.', ['dormo', 'dormi', 'dorme'], 0, 'Dormire: dorm- + -o → dormo.'),
      present('p5-2', 'Tu ___ domani mattina. (partire)', 'Odjíždíš zítra ráno.', 'Doplň tvar pro tu.', ['parto', 'parti', 'parte'], 1, 'Partire: part- + -i → parti.'),
      present('p5-3', 'Marta ___ la finestra. (aprire)', 'Marta otevírá okno.', 'Doplň tvar pro lei.', ['apro', 'apri', 'apre'], 2, 'Aprire: apr- + -e → apre.'),
      present('p5-4', 'Noi ___ la musica. (sentire)', 'Slyšíme hudbu.', 'Doplň tvar pro noi.', ['sentiamo', 'sentite', 'sentono'], 0, 'Sentire: sent- + -iamo → sentiamo.'),
      present('p5-5', 'Voi ___ la cena. (servire)', 'Podáváte večeři.', 'Doplň tvar pro voi.', ['serviamo', 'servite', 'servono'], 1, 'Servire: serv- + -ite → servite.'),
      present('p5-6', 'I bambini ___ poco. (dormire)', 'Děti málo spí.', 'Doplň tvar pro loro.', ['dormite', 'dorme', 'dormono'], 2, 'I bambini jsou loro: dormono.'),
      present('p5-7', 'Io ___ la porta. (aprire)', 'Otevírám dveře.', 'Doplň tvar pro io.', ['apro', 'apri', 'apre'], 0, 'Aprire: pro io apro.'),
      present('p5-8', 'Noi ___ alle sette. (partire)', 'Odjíždíme v sedm.', 'Doplň tvar pro noi.', ['partite', 'partiamo', 'partono'], 1, 'Partire: part- + -iamo → partiamo.'),
      present('p5-9', 'Tu ___ questo profumo? (sentire)', 'Cítíš tuto vůni?', 'Doplň otázku.', ['senti', 'sento', 'sente'], 0, 'Pro tu: senti.'),
      present('p5-10', 'I camerieri ___ ai tavoli. (servire)', 'Číšníci obsluhují u stolů.', 'Doplň tvar pro loro.', ['servite', 'serve', 'servono'], 2, 'I camerieri jsou loro: servono.'),
    ],
  },
  {
    id: 'present-ire-isc', number: 6, title: 'Slovesa na -ire II', description: 'Typ finire s vložkou -isc-',
    reminderTitle: 'VLOŽKA -ISC-', stemReminder: 'io -isco · tu -isci · lui/lei -isce · noi -iamo · voi -ite · loro -iscono',
    questions: [
      present('p6-1', 'Io ___ il lavoro alle cinque. (finire)', 'Končím práci v pět.', 'Doplň tvar pro io.', ['finisco', 'fino', 'finisci'], 0, 'Finire patří k typu -isc-: io finisco.'),
      present('p6-2', 'Tu ___ la domanda? (capire)', 'Rozumíš otázce?', 'Doplň tvar pro tu.', ['capisco', 'capisci', 'capisce'], 1, 'Capire: tu capisci.'),
      present('p6-3', 'Paolo ___ il tè. (preferire)', 'Paolo dává přednost čaji.', 'Doplň tvar pro lui.', ['preferisco', 'preferisci', 'preferisce'], 2, 'Paolo je lui: preferisce.'),
      present('p6-4', 'Noi ___ la cucina. (pulire)', 'Uklízíme kuchyň.', 'Doplň tvar pro noi.', ['puliamo', 'pulisciamo', 'pulite'], 0, 'U noi se -isc- nevkládá: puliamo.'),
      present('p6-5', 'Voi ___ il pacco oggi. (spedire)', 'Posíláte balík dnes.', 'Doplň tvar pro voi.', ['spedisiamo', 'spedite', 'spediscono'], 1, 'U voi se -isc- nevkládá: spedite.'),
      present('p6-6', 'Le aziende ___ nuove case. (costruire)', 'Firmy stavějí nové domy.', 'Doplň tvar pro loro.', ['costruite', 'costruisce', 'costruiscono'], 2, 'Le aziende jsou loro: costruiscono.'),
      present('p6-7', 'Io ___ un ristorante tranquillo. (preferire)', 'Dávám přednost klidné restauraci.', 'Doplň tvar pro io.', ['preferisco', 'prefero', 'preferisci'], 0, 'Preferire: io preferisco.'),
      present('p6-8', 'Noi ___ tutto chiaramente. (capire)', 'Všemu jasně rozumíme.', 'Doplň tvar pro noi.', ['capite', 'capiamo', 'capisciamo'], 1, 'U noi bez -isc-: capiamo.'),
      present('p6-9', 'Tu ___ la camera ogni giorno. (pulire)', 'Uklízíš pokoj každý den.', 'Doplň tvar pro tu.', ['pulisci', 'puli', 'pulisce'], 0, 'Pulire: tu pulisci.'),
      present('p6-10', 'Gli studenti ___ l’esercizio. (finire)', 'Studenti dokončují cvičení.', 'Doplň tvar pro loro.', ['finite', 'finisce', 'finiscono'], 2, 'Gli studenti jsou loro: finiscono.'),
    ],
  },
];
