import { Exercise, ExerciseSet } from './exercises';

const reflexive = (
  id: string,
  sentence: string,
  translation: string,
  task: string,
  options: [string, string, string],
  correct: number,
  explanation: string,
): Exercise => ({ id, kind: 'Zvratná slovesa', sentence, translation, task, options, correct, explanation });

export const reflexiveExerciseSets: ExerciseSet[] = [
  {
    id: 'reflexive-present', number: 1, title: 'Přítomný čas I', description: 'Zvratná zájmena a základní tvary',
    reminderTitle: 'ZVRATNÁ ZÁJMENA', stemReminder: 'io mi · tu ti · lui/lei si · noi ci · voi vi · loro si',
    questions: [
      reflexive('r1-1', 'Io ___ alle sette. (svegliarsi)', 'Budím se v sedm.', 'Doplň celý správný tvar.', ['mi sveglio', 'ti svegli', 'si sveglia'], 0, 'Pro io použijeme mi + sveglio → mi sveglio.'),
      reflexive('r1-2', 'Tu ___ molto presto. (alzarsi)', 'Vstáváš velmi brzy.', 'Doplň celý správný tvar.', ['mi alzo', 'ti alzi', 'si alza'], 1, 'Pro tu použijeme ti + alzi → ti alzi.'),
      reflexive('r1-3', 'Marco ___ prima di cena. (lavarsi)', 'Marco se myje před večeří.', 'Doplň celý správný tvar.', ['ti lavi', 'si lavano', 'si lava'], 2, 'Marco je lui: si + lava → si lava.'),
      reflexive('r1-4', 'Noi ___ per uscire. (prepararsi)', 'Připravujeme se na odchod.', 'Doplň celý správný tvar.', ['ci prepariamo', 'vi preparate', 'si preparano'], 0, 'Pro noi použijeme ci + prepariamo.'),
      reflexive('r1-5', 'Voi ___ in camera. (vestirsi)', 'Oblékáte se v pokoji.', 'Doplň celý správný tvar.', ['ci vestiamo', 'vi vestite', 'si vestono'], 1, 'Pro voi použijeme vi + vestite.'),
      reflexive('r1-6', 'I bambini ___ subito. (addormentarsi)', 'Děti okamžitě usínají.', 'Doplň celý správný tvar.', ['vi addormentate', 'si addormenta', 'si addormentano'], 2, 'I bambini jsou loro: si + addormentano.'),
      reflexive('r1-7', 'Io ___ davanti allo specchio. (pettinarsi)', 'Češu se před zrcadlem.', 'Doplň celý správný tvar.', ['mi pettino', 'ti pettini', 'si pettina'], 0, 'Pro io použijeme mi + pettino.'),
      reflexive('r1-8', 'Noi ___ dopo il lavoro. (rilassarsi)', 'Odpočíváme po práci.', 'Doplň celý správný tvar.', ['vi rilassate', 'ci rilassiamo', 'si rilassano'], 1, 'Pro noi použijeme ci + rilassiamo.'),
      reflexive('r1-9', 'Come ___? (chiamarsi, tu)', 'Jak se jmenuješ?', 'Doplň celý správný tvar.', ['mi chiamo', 'si chiama', 'ti chiami'], 2, 'Otázka je na tu: Come ti chiami?'),
      reflexive('r1-10', 'Le bambine ___ le mani. (lavarsi)', 'Děvčata si myjí ruce.', 'Doplň celý správný tvar.', ['si lavano', 'ci laviamo', 'vi lavate'], 0, 'Le bambine jsou loro: si lavano.'),
    ],
  },
  {
    id: 'reflexive-word-order', number: 2, title: 'Přítomný čas II', description: 'Slovosled, zápor a otázky',
    reminderTitle: 'SLOVOSLED', stemReminder: 'Zájmeno stojí před určitým slovesem: mi alzo. V záporu: non mi alzo.',
    questions: [
      reflexive('r2-1', 'Io non ___ mai tardi. (alzarsi)', 'Nikdy nevstávám pozdě.', 'Vyber správný záporný tvar.', ['mi alzo', 'alzo mi', 'si alzo'], 0, 'Zvratné zájmeno stojí před slovesem: non mi alzo.'),
      reflexive('r2-2', '___ ogni mattina? (lavarsi, tu)', 'Myješ se každé ráno?', 'Doplň otázku.', ['Mi lavi', 'Ti lavi', 'Si lava'], 1, 'Pro tu použijeme ti lavi; otázka nemění slovosled.'),
      reflexive('r2-3', 'Laura ___ prima di uscire. (truccarsi)', 'Laura se líčí před odchodem.', 'Doplň správný tvar.', ['ti trucchi', 'si truccano', 'si trucca'], 2, 'Laura je lei: si trucca.'),
      reflexive('r2-4', 'Noi non ___ durante la settimana. (riposarsi)', 'Během týdne neodpočíváme.', 'Doplň záporný tvar.', ['ci riposiamo', 'vi riposate', 'si riposano'], 0, 'Non stojí před zvratným zájmenem: non ci riposiamo.'),
      reflexive('r2-5', 'A che ora ___? (svegliarsi, voi)', 'V kolik hodin se budíte?', 'Doplň otázku.', ['ci svegliamo', 'vi svegliate', 'si svegliano'], 1, 'Pro voi použijeme vi svegliate.'),
      reflexive('r2-6', 'Paolo e Anna non ___ presto. (addormentarsi)', 'Paolo a Anna neusínají brzy.', 'Doplň správný tvar.', ['vi addormentate', 'si addormenta', 'si addormentano'], 2, 'Paolo e Anna jsou loro: non si addormentano.'),
      reflexive('r2-7', 'Io ___ sempre prima di colazione. (farsi la doccia)', 'Vždy se sprchuji před snídaní.', 'Doplň celý správný tvar.', ['mi faccio la doccia', 'faccio mi la doccia', 'si fa la doccia'], 0, 'Zvratné zájmeno mi stojí před určitým slovesem faccio.'),
      reflexive('r2-8', 'Noi ___ in fretta la mattina. (vestirsi)', 'Ráno se rychle oblékáme.', 'Doplň správný tvar.', ['vi vestite', 'ci vestiamo', 'si vestono'], 1, 'Pro noi: ci vestiamo.'),
      reflexive('r2-9', 'Perché non ___? (sedersi, tu)', 'Proč si nesedneš?', 'Doplň zápornou otázku.', ['mi siedo', 'si siede', 'ti siedi'], 2, 'Pro tu použijeme ti siedi: Perché non ti siedi?'),
      reflexive('r2-10', 'I ragazzi ___ dopo la partita. (cambiarsi)', 'Chlapci se po zápase převlékají.', 'Doplň správný tvar.', ['si cambiano', 'ci cambiamo', 'vi cambiate'], 0, 'I ragazzi jsou loro: si cambiano.'),
    ],
  },
  {
    id: 'reflexive-infinitive', number: 3, title: 'Zvratné infinitivy', description: 'Dovere, potere, volere + infinitiv',
    reminderTitle: 'DVĚ SPRÁVNÉ POZICE', stemReminder: 'Mi devo alzare = devo alzarmi. V úloze vždy dodrž požadovanou pozici zájmena.',
    questions: [
      reflexive('r3-1', 'Io devo ___. (svegliarsi)', 'Musím se probudit.', 'Připoj zájmeno k infinitivu.', ['svegliarmi', 'mi svegliare', 'svegliarsi'], 0, 'Po připojení k infinitivu se -si změní podle osoby: svegliar-mi.'),
      reflexive('r3-2', 'Tu ___ vestire. (dovere + vestirsi)', 'Musíš se obléknout.', 'Postav zájmeno před modální sloveso.', ['mi devi', 'ti devi', 'devi ti'], 1, 'Pro tu stojí ti před určitým slovesem: ti devi vestire.'),
      reflexive('r3-3', 'Marta vuole ___. (riposarsi)', 'Marta si chce odpočinout.', 'Připoj zájmeno k infinitivu.', ['riposarti', 'riposarci', 'riposarsi'], 2, 'Marta je lei, proto infinitiv končí -si: riposarsi.'),
      reflexive('r3-4', 'Noi ___ preparare. (dovere + prepararsi)', 'Musíme se připravit.', 'Postav zájmeno před modální sloveso.', ['ci dobbiamo', 'vi dovete', 'si devono'], 0, 'Pro noi: ci dobbiamo preparare.'),
      reflexive('r3-5', 'Voi potete ___. (sedersi)', 'Můžete si sednout.', 'Připoj zájmeno k infinitivu.', ['sederci', 'sedervi', 'sedersi'], 1, 'Pro voi připojíme -vi: sedervi.'),
      reflexive('r3-6', 'I bambini ___ lavare le mani. (dovere + lavarsi)', 'Děti si musí umýt ruce.', 'Postav zájmeno před modální sloveso.', ['vi dovete', 'si deve', 'si devono'], 2, 'I bambini jsou loro: si devono lavare.'),
      reflexive('r3-7', 'Io ___ rilassare. (volere + rilassarsi)', 'Chci si odpočinout.', 'Postav zájmeno před modální sloveso.', ['mi voglio', 'ti vuoi', 'voglio mi'], 0, 'Pro io: mi voglio rilassare.'),
      reflexive('r3-8', 'Noi vogliamo ___. (divertirsi)', 'Chceme se bavit.', 'Připoj zájmeno k infinitivu.', ['divertirvi', 'divertirci', 'divertirsi'], 1, 'Pro noi připojíme -ci: divertirci.'),
      reflexive('r3-9', 'Tu puoi ___. (fermarsi)', 'Můžeš se zastavit.', 'Připoj zájmeno k infinitivu.', ['fermarmi', 'fermarsi', 'fermarti'], 2, 'Pro tu připojíme -ti: fermarti.'),
      reflexive('r3-10', 'Gli studenti ___ concentrare. (dovere + concentrarsi)', 'Studenti se musí soustředit.', 'Postav zájmeno před modální sloveso.', ['si devono', 'ci dobbiamo', 'vi dovete'], 0, 'Gli studenti jsou loro: si devono concentrare.'),
    ],
  },
  {
    id: 'reflexive-imperative', number: 4, title: 'Zvratný imperativ', description: 'Rozkazy a zákazy',
    reminderTitle: 'IMPERATIV', stemReminder: 'Kladně se zájmeno připojuje: alzati, alzatevi. Záporné tu: non alzarti.',
    questions: [
      reflexive('r4-1', '___, Marco! (alzarsi, tu)', 'Vstaň, Marco!', 'Vytvoř kladný rozkaz.', ['Alzati', 'Ti alza', 'Alzarsi'], 0, 'U kladného imperativu tu se -ti připojí: alza + ti → alzati.'),
      reflexive('r4-2', '___ le mani! (lavarsi, tu)', 'Umyj si ruce!', 'Vytvoř kladný rozkaz.', ['Ti lava', 'Lavati', 'Lavarsi'], 1, 'Lava + ti → lavati.'),
      reflexive('r4-3', '___ in fretta! (vestirsi, tu)', 'Rychle se obleč!', 'Vytvoř kladný rozkaz.', ['Vestivi', 'Ti vesti', 'Vestiti'], 2, 'Vesti + ti → vestiti.'),
      reflexive('r4-4', '___, ragazzi! (svegliarsi, voi)', 'Probuďte se, děti!', 'Vytvoř kladný rozkaz.', ['Svegliatevi', 'Vi svegliate', 'Svegliarsi'], 0, 'Svegliate + vi → svegliatevi.'),
      reflexive('r4-5', '___ per la foto! (prepararsi, voi)', 'Připravte se na fotografii!', 'Vytvoř kladný rozkaz.', ['Vi preparate', 'Preparatevi', 'Preparati'], 1, 'Preparate + vi → preparatevi.'),
      reflexive('r4-6', '___ un momento! (riposarsi, noi)', 'Na chvíli si odpočiňme!', 'Vytvoř rozkaz pro noi.', ['Ci riposiamo', 'Riposatevi', 'Riposiamoci'], 2, 'Riposi(a)mo + ci → riposiamoci; před ci odpadá poslední -o.'),
      reflexive('r4-7', 'Non ___! (preoccuparsi, tu)', 'Nedělej si starosti!', 'Vytvoř záporný rozkaz.', ['preoccuparti', 'ti preoccupa', 'preoccupati'], 0, 'Záporný imperativ tu používá non + infinitiv se zájmenem: non preoccuparti.'),
      reflexive('r4-8', 'Non ___ così tardi! (alzarsi, tu)', 'Nevstávej tak pozdě!', 'Vytvoř záporný rozkaz.', ['ti alzi', 'alzarti', 'alzati'], 1, 'Non + infinitiv alzarti → non alzarti.'),
      reflexive('r4-9', '___ qui, signora! (sedersi, Lei)', 'Posaďte se zde, paní!', 'Vytvoř zdvořilý rozkaz.', ['Siediti', 'Sedetevi', 'Si sieda'], 2, 'Zdvořilý imperativ Lei má zájmeno před slovesem: si sieda.'),
      reflexive('r4-10', '___, è tardi! (sbrigarsi, noi)', 'Pospěšme si, je pozdě!', 'Vytvoř rozkaz pro noi.', ['Sbrighiamoci', 'Ci sbrighiamo', 'Sbrigatevi'], 0, 'Sbrighiamo + ci → sbrighiamoci.'),
    ],
  },
  {
    id: 'reflexive-reciprocal', number: 5, title: 'Vzájemnost a význam', description: 'Ci/vi/si navzájem a častá slovesa',
    reminderTitle: 'ZVRATNÉ × VZÁJEMNÉ', stemReminder: 'Ci vediamo = vidíme se / navzájem. Si scrivono = píšou si. Význam určuje kontext.',
    questions: [
      reflexive('r5-1', 'Noi ___ ogni sabato. (vedersi)', 'Vídáme se každou sobotu.', 'Doplň správný tvar.', ['ci vediamo', 'vi vedete', 'si vedono'], 0, 'Noi + vzájemný děj → ci vediamo.'),
      reflexive('r5-2', 'Voi ___ spesso? (incontrarsi)', 'Setkáváte se často?', 'Doplň správný tvar.', ['ci incontriamo', 'vi incontrate', 'si incontrano'], 1, 'Pro voi použijeme vi incontrate.'),
      reflexive('r5-3', 'Paolo e Giulia ___ ogni giorno. (scriversi)', 'Paolo a Giulia si každý den píšou.', 'Doplň správný tvar.', ['vi scrivete', 'si scrive', 'si scrivono'], 2, 'Dvě osoby jsou loro: si scrivono.'),
      reflexive('r5-4', 'Noi ___ quando arriviamo. (salutarsi)', 'Pozdravíme se, když přijdeme.', 'Doplň správný tvar.', ['ci salutiamo', 'vi salutate', 'si salutano'], 0, 'Noi + vzájemný děj → ci salutiamo.'),
      reflexive('r5-5', 'Voi ___ sempre. (aiutarsi)', 'Vždy si navzájem pomáháte.', 'Doplň správný tvar.', ['ci aiutiamo', 'vi aiutate', 'si aiutano'], 1, 'Pro voi použijeme vi aiutate.'),
      reflexive('r5-6', 'Le sorelle ___ molto bene. (capirsi)', 'Sestry si velmi dobře rozumějí.', 'Doplň správný tvar.', ['vi capite', 'si capisce', 'si capiscono'], 2, 'Le sorelle jsou loro: si capiscono.'),
      reflexive('r5-7', 'Io non ___ bene oggi. (sentirsi)', 'Dnes se necítím dobře.', 'Doplň správný tvar.', ['mi sento', 'ti senti', 'si sente'], 0, 'Sentirsi ve významu cítit se: io mi sento.'),
      reflexive('r5-8', 'Tu ___ di chiudere la porta? (ricordarsi)', 'Vzpomeneš si zavřít dveře?', 'Doplň správný tvar.', ['mi ricordo', 'ti ricordi', 'si ricorda'], 1, 'Pro tu: ti ricordi.'),
      reflexive('r5-9', 'Luca ___ subito dell’errore. (accorgersi)', 'Luca si chyby okamžitě všimne.', 'Doplň správný tvar.', ['ti accorgi', 'si accorgono', 'si accorge'], 2, 'Luca je lui: si accorge.'),
      reflexive('r5-10', 'Noi ___ molto insieme. (divertirsi)', 'Společně se hodně bavíme.', 'Doplň správný tvar.', ['ci divertiamo', 'vi divertite', 'si divertono'], 0, 'Pro noi: ci divertiamo.'),
    ],
  },
];
